### ISSUE TITLE
Fail to connect with 'wss://testnet-harbour.datahighway.com'

### ISSUE THREAD

**Issue by zhbh** [DataHighway-DHX/app#3]
this is my branch [develop_sam](https://github.com/DataHighway-DHX/app/tree/develop_sam), and run this project, it would show this issue:

I/chromium(15810): [INFO:CONSOLE(33)] "WebSocket connection to 'wss://testnet-harbour.datahighway.com/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED", source:  (33)

no more detail to view in the error log.

**Comment by zhbh** [comment]
it adds costom type to this [way.](https://github.com/DataHighway-DHX/app/blob/4287ee22be62f9d45a96c3c8cd5ffd6660cbd11d/lib/polkadot_js_service/src/index.js#L24), and this our [types](https://github.com/DataHighway-DHX/app/blob/develop_sam/lib/polkadot_js_service/src/utils/costom_types.js).

**Comment by cgroeschel** [comment]
on the server side I see the request in reverse-proxy log like this:
`reverse-proxy_nginx_1[16982]: 101.112.209.41 - - [27/May/2020:14:17:01 +0000] "GET / HTTP/1.1" 101 371051 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36" "-"`

**Comment by cgroeschel** [comment]
ERR_NAME_NOT_RESOLVED indicates issues resolving the hostname to the IP. Can you try:
- to clear browser cache
- ping the hostname and see if it resolves ok by your OS

**Comment by sheenhx** [comment]
seems like 101.112.209.41 is Australia, Sydney

**Comment by sheenhx** [comment]
Sam connected wss from chrome at home, so network is fine

**Comment by sheenhx** [comment]
problem solved, it is android emulator DNS thing

**Comment by zhbh** [comment]
The issue was solved. That because is that my android simulator can be instability connected to the network on my laptop.
