### ISSUE TITLE
Unhandled Exception: Bad state: No element

### ISSUE THREAD

**Issue by zhbh** [DataHighway-DHX/app#4]
hi,@ltfschoen. When I debug interface `getAccountLockedClaimsApprovedOfMXCAmountFromDataHighwayMXCMiningContract`, it reports one exception, which it ran its [code](https://github.com/DataHighway-DHX/app/blob/b828b47d93ed425d623788d7a649e627b1ac22bb/lib/service/ethereumApi/apiMiningMXC.dart#L36).

and My abiCode is [here](https://github.com/DataHighway-DHX/app/blob/develop_sam/assets/data/abi_datahighway_mxc_mining_mainnet.json).

**Flutter Excetpion:**
`E/flutter (11893): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Bad state: No element

E/flutter (11893): #0      ListMixin.singleWhere  (dart:collection/list.dart:185:5)

E/flutter (11893): #1      DeployedContract.event 
package:web3dart/…/contracts/deployed_contract.dart:42

E/flutter (11893): #2      EthereumApiMiningMXC.getAccountLockedClaimsApprovedOfMXCAmountFromDataHighwayMXCMiningContract 
package:polka_wallet/…/ethereumApi/apiMiningMXC.dart:421

E/flutter (11893): <asynchronous suspension>

E/flutter (11893): #3      Ethereum.fetchMXCLockedClaimsApproved 
package:polka_wallet/…/ethereumApi/api.dart:68

E/flutter (11893): <asynchronous suspension>

E/flutter (11893): #4      Ethereum.init 
package:polka_wallet/…/ethereumApi/api.dart:40

E/flutter (11893): <asynchronous suspension>

E/flutter (11893): #5      _WalletAppState._initStore 
package:polka_wallet/app.dart:104

E/flutter (11893): #6      _asyncThenWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:73:64)

E/flutter (11893): #7      _rootRunUnary  (dart:async/zone.dart:1134:38)

E/flutter (11893): #8      _CustomZone.runUnary  (dart:async/zone.dart:1031:19)

E/flutter (11893): #9      _FutureListener.handleValue  (dart:async/future_impl.dart:139:18)

E/flutter (11893): #10     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:680:45)

E/flutter (11893): #11     Future._propagateToListeners  (dart:async/future_impl.dart:709:32)

E/flutter (11893): #12     Future._completeWithValue  (dart:async/future_impl.dart:524:5)

E/flutter (11893): #13     _AsyncAwaitCompleter.complete  (dart:async-patch/async_patch.dart:32:15)
`

It causes that I can not get the right result.

**Comment by ltfschoen** [comment]
I've in the process of updating the smart contract here https://github.com/DataHighway-DHX/mining/pull/11 and trying to get it to integrate with the app.

**Comment by ltfschoen** [comment]
@zhbh could you please try using the latest .env that i provided for you to use in WeChat, along with the latest commit in the develop_sam branch and see if we can close this issue?
