### ISSUE TITLE
WebSocketChannelException: was not upgraded to websocket

### ISSUE THREAD

**Issue by zhbh** [DataHighway-DHX/app#5]
hi, @ltfschoen. When I ran [the code](https://github.com/DataHighway-DHX/app/blob/91a1a7b6f2f3dba81c814da6703abc4479af0197/lib/service/ethereumApi/apiAssetsMXC.dart#L53), it appears the issue as follows, but it can not stop me to get the correct result. However, I think it should have some effects if it runs successfully. 

**The Flutter Exception:**
`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: WebSocketChannelException: WebSocketChannelException: WebSocketException: Connection to 'https://mainnet.infura.io:0/v3/031a0a2b799c44a0b3539c1e86e6cbd9#' was not upgraded to websocket`

**Comment by ltfschoen** [comment]
@zhbh could you please try using the latest .env that i provided for you to use along with the latest commit in the develop_sam branch and see if we can close this issue?

Note that in the error message you've shown, it appears as though it was connecting to Mainnet on Infura.
However, if you use the latest .env file contents that I shared with you, it should use Ropsten Testnet on Infura.
